
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Heloisa Rafa Gabi", email = "rafaelaalbano70@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.7.0",
]
