# Generated by Django 4.2.5 on 2023-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourfood', '0002_bebidas_sobremesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bebidas',
        ),
        migrations.DeleteModel(
            name='Lanches',
        ),
        migrations.DeleteModel(
            name='Sobremesas',
        ),
    ]
