# Generated by Django 4.2.5 on 2023-10-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourfood', '0003_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fomadepagamento',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ourfood.pagamento'),
            preserve_default=False,
        ),
    ]
