# Generated by Django 4.2.6 on 2023-10-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ourfood", "0003_delete_administrador_remove_pedido_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itempedido",
            name="pedido",
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="ourfood.produto",
            ),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
