# Generated by Django 4.2.5 on 2023-09-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ourfood", "0004_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="teste",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
