# Generated by Django 4.2.7 on 2023-11-06 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ourfood", "0007_alter_itempedido_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
