# Generated by Django 4.2.7 on 2023-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ourfood", "0008_pedido_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="produto",
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_pagamento",
            field=models.IntegerField(
                choices=[
                    (1, "Cartão de Crédito"),
                    (2, "Cartão de Débito"),
                    (3, "PIX"),
                    (4, "Boleto"),
                    (5, "Transferência Bancária"),
                    (6, "Dinheiro"),
                    (7, "Outro"),
                ],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="FomaDePagamento",
        ),
        migrations.DeleteModel(
            name="Pagamento",
        ),
    ]
